language: generic

script:
  - python3 -m pip install setuptools
  - python3 -m pip install .
  - ./tests/platform_install.sh
  - ./tests/platform_update.sh
  - ./tests/project_start.sh
after_success:
  - echo "DONE!"

jobs:
    include:
        - os: linux
          dist: bionic
          install:
            - sudo apt-get install python3-pip
        - os: osx
          osx_image: xcode10
        - os: osx
          osx_image: xcode11.3
